# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15sYQRVo70uprLpbzGMVK1tLBOHyDQ4qR
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import os
# from datetime import datetime
# import base64
# 
# import streamlit as st
# import pandas as pd
# from pypdf import PdfReader
# 
# # LangChain imports
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.vectorstores import FAISS
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain.prompts import PromptTemplate
# from langchain.chains import RetrievalQA
# 
# 
# # ---------- PDF HELPERS ----------
# 
# def get_pdf_text(pdf_docs):
#     """Extract raw text from multiple uploaded PDF files."""
#     text = ""
#     for pdf in pdf_docs:
#         pdf_reader = PdfReader(pdf)
#         for page in pdf_reader.pages:
#             page_text = page.extract_text()
#             if page_text:
#                 text += page_text + "\n"
#     return text
# 
# 
# def get_text_chunks(text, chunk_size=1000, chunk_overlap=200):
#     """Split long text into smaller chunks for embeddings."""
#     splitter = RecursiveCharacterTextSplitter(
#         chunk_size=chunk_size,
#         chunk_overlap=chunk_overlap,
#         length_function=len,
#     )
#     chunks = splitter.split_text(text)
#     return chunks
# 
# 
# def build_vector_store(text_chunks):
#     """Create FAISS vector store from text chunks using HuggingFace embeddings."""
#     # Local embedding model (no paid API needed)
#     embeddings = HuggingFaceEmbeddings(
#         model_name="sentence-transformers/all-MiniLM-L6-v2"
#     )
#     vector_store = FAISS.from_texts(text_chunks, embedding=embeddings)
#     return vector_store
# 
# 
# # ---------- LLM + QA CHAIN ----------
# 
# def get_qa_chain(vector_store, google_api_key):
#     """Create a RetrievalQA chain using Gemini as LLM."""
#     os.environ["GOOGLE_API_KEY"] = google_api_key
# 
#     # You can change model name if needed (e.g., "gemini-1.5-flash-latest")
#     llm = ChatGoogleGenerativeAI(
#         model="gemini-1.5-flash",
#         temperature=0.3,
#     )
# 
#     # 🔹 If you want finance-focused answers, keep those lines.
#     # 🔹 If you want generic answers for any PDF, remove the finance part.
#     prompt_template = """
# You are a helpful assistant answering questions based ONLY on the given context.
# 
# Instructions:
# - Use only the information from the context.
# - If the answer is not present in the context, say clearly: "Information not found in the PDF."
# - Be clear and structured in your answer.
# - Do NOT hallucinate or invent data.
# 
# Context:
# {context}
# 
# Question:
# {question}
# 
# Answer:
#     """
# 
#     prompt = PromptTemplate(
#         template=prompt_template,
#         input_variables=["context", "question"],
#     )
# 
#     chain = RetrievalQA.from_chain_type(
#         llm=llm,
#         chain_type="stuff",
#         retriever=vector_store.as_retriever(search_kwargs={"k": 4}),
#         chain_type_kwargs={"prompt": prompt},
#         return_source_documents=False,
#     )
#     return chain
# 
# 
# # ---------- CONVERSATION + UI LOGIC ----------
# 
# def run_qa(
#     question: str,
#     qa_chain,
#     pdf_names,
#     conversation_history: list,
# ):
#     """Run a question through the QA chain and display chat-style UI."""
#     if qa_chain is None:
#         st.warning("Please upload PDFs and click 'Submit & Process' first.")
#         return
# 
#     with st.spinner("Thinking..."):
#         result = qa_chain({"query": question})
#         answer = result["result"]
# 
#     # Save to conversation history
#     timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
#     conversation_history.append(
#         (question, answer, "Gemini (Google AI)", timestamp, ", ".join(pdf_names))
#     )
# 
#     # ------ Chat-style display for current Q&A ------
#     st.markdown(
#         """
#         <style>
#             .chat-message {
#                 padding: 1rem;
#                 border-radius: 0.5rem;
#                 margin-bottom: 0.8rem;
#                 display: flex;
#                 gap: 0.8rem;
#             }
#             .chat-message.user {
#                 background-color: #2b313e;
#             }
#             .chat-message.bot {
#                 background-color: #475063;
#             }
#             .chat-message .avatar img {
#                 max-width: 48px;
#                 max-height: 48px;
#                 border-radius: 50%;
#                 object-fit: cover;
#             }
#             .chat-message .message {
#                 color: #ffffff;
#                 width: 100%;
#             }
#         </style>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#     # Current question
#     st.markdown(
#         f"""
#         <div class="chat-message user">
#             <div class="avatar">
#                 <img src="https://i.ibb.co/CKpTnWr/user-icon-2048x2048-ihoxz4vq.png">
#             </div>
#             <div class="message">{question}</div>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#     # Current answer
#     st.markdown(
#         f"""
#         <div class="chat-message bot">
#             <div class="avatar">
#                 <img src="https://i.ibb.co/wNmYHsx/langchain-logo.webp">
#             </div>
#             <div class="message">{answer}</div>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#     # ------ Previous conversation (history) ------
#     if len(conversation_history) > 1:
#         st.markdown("---")
#         st.subheader("Previous Q&A")
#         for q, a, model_name, ts, pdf_name in reversed(conversation_history[:-1]):
#             st.markdown(
#                 f"""
#                 <div class="chat-message user">
#                     <div class="avatar">
#                         <img src="https://i.ibb.co/CKpTnWr/user-icon-2048x2048-ihoxz4vq.png">
#                     </div>
#                     <div class="message">{q}</div>
#                 </div>
#                 <div class="chat-message bot">
#                     <div class="avatar">
#                         <img src="https://i.ibb.co/wNmYHsx/langchain-logo.webp">
#                     </div>
#                     <div class="message">{a}</div>
#                 </div>
#                 """,
#                 unsafe_allow_html=True,
#             )
# 
#     # ------ Download conversation as CSV ------
#     if len(conversation_history) > 0:
#         df = pd.DataFrame(
#             conversation_history,
#             columns=["Question", "Answer", "Model", "Timestamp", "PDF Name"],
#         )
#         csv = df.to_csv(index=False)
#         b64 = base64.b64encode(csv.encode()).decode()
#         href = (
#             f'<a href="data:file/csv;base64,{b64}" '
#             f'download="conversation_history.csv">'
#             f'<button>Download conversation history as CSV</button></a>'
#         )
#         st.sidebar.markdown(href, unsafe_allow_html=True)
# 
# 
# # ---------- STREAMLIT MAIN APP ----------
# 
# def main():
#     st.set_page_config(page_title="Chat with PDFs (RAG)", page_icon="📚", layout="wide")
#     st.title("📚 Chat with your PDF documents")
# 
#     # Initialise session state
#     if "conversation_history" not in st.session_state:
#         st.session_state.conversation_history = []
#     if "vector_store" not in st.session_state:
#         st.session_state.vector_store = None
#     if "pdf_names" not in st.session_state:
#         st.session_state.pdf_names = []
# 
#     # ----- Sidebar -----
#     st.sidebar.title("Settings")
# 
#     # Social links (optional)
#     st.sidebar.markdown(
#         """
#         <small>Built with LangChain, HuggingFace & Gemini</small>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#     # Google API key
#     google_api_key = st.sidebar.text_input(
#         "🔑 Enter your Google API Key", type="password"
#     )
#     st.sidebar.markdown(
#         '[Get an API key](https://ai.google.dev/)'
#     )
# 
#     # PDF upload
#     pdf_docs = st.sidebar.file_uploader(
#         "📂 Upload your PDF files",
#         type=["pdf"],
#         accept_multiple_files=True,
#     )
# 
#     if st.sidebar.button("Submit & Process"):
#         if not google_api_key:
#             st.sidebar.warning("Please enter your Google API Key first.")
#         elif not pdf_docs:
#             st.sidebar.warning("Please upload at least one PDF.")
#         else:
#             with st.spinner("Reading and indexing PDFs..."):
#                 raw_text = get_pdf_text(pdf_docs)
#                 if not raw_text.strip():
#                     st.warning("No extractable text found in the PDFs.")
#                 else:
#                     chunks = get_text_chunks(raw_text)
#                     vector_store = build_vector_store(chunks)
#                     st.session_state.vector_store = vector_store
#                     st.session_state.pdf_names = [pdf.name for pdf in pdf_docs]
#                     st.success(
#                         f"Processing complete ✅ | Characters: {len(raw_text)}, Chunks: {len(chunks)}"
#                     )
# 
#     st.markdown("### Ask a question about your PDFs")
#     user_question = st.text_input("Type your question and press Enter")
# 
#     if user_question:
#         if st.session_state.vector_store is None:
#             st.warning("Please upload PDFs and click 'Submit & Process' first.")
#         elif not google_api_key:
#             st.warning("Please enter your Google API Key in the sidebar.")
#         else:
#             qa_chain = get_qa_chain(st.session_state.vector_store, google_api_key)
#             run_qa(
#                 user_question,
#                 qa_chain,
#                 st.session_state.pdf_names,
#                 st.session_state.conversation_history,
#             )
# 
# 
# if __name__ == "__main__":
#     main()
#