# -*- coding: utf-8 -*-
"""RAG based model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCNOo4kSw2MN15AwEGrhSIfPip6g2wUl

Step 1: Install required libraries

Libraries
"""

# Streamlit UI (only if you're using the UI version)
import streamlit as st

# PDF reader
from PyPDF2 import PdfReader

# Data handling
import pandas as pd
import base64
import os
from datetime import datetime

# PDF reader
from pypdf import PdfReader

# Text splitter (correct package for langchain 1.x)
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Vector DB + Embeddings (community package)
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

# Gemini LLM
from langchain_google_genai import ChatGoogleGenerativeAI

# Prompt + LCEL (modern chain system)
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough # Added this import

import google.generativeai as genai
from langchain_google_genai import ChatGoogleGenerativeAI
import os

api_key = input("Enter your Google API Key: ")
genai.configure(api_key=api_key)
os.environ["GOOGLE_API_KEY"] = api_key

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-flash-latest"  # or "gemini-2.0-flash"
)
print(llm.invoke("Hello Sunidhi!"))

"""STEP 2 — Create the free embeddings model"""

from pypdf import PdfReader

def get_pdf_text(pdf_files):
    text = ""
    for pdf in pdf_files:
        reader = PdfReader(pdf)
        for page in reader.pages:
            text += page.extract_text() or ""
    return text

# Example usage:
pdf_paths = ["/content/MAIN_REPORT[1] (1).pdf"]  # replace with your actual PDF path
raw_text = get_pdf_text(pdf_paths)
print("Characters extracted:", len(raw_text))

"""STEP 4 — Load PDFs and extract text"""

from sentence_transformers import SentenceTransformer

# FREE embedding model
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

def get_embeddings(text_chunks):
    embeddings = embedding_model.encode(text_chunks, convert_to_tensor=False)
    return embeddings

# Generate embeddings
embeddings = get_embeddings(chunks)

print("Number of embeddings:", len(embeddings))
print("Embedding dimension:", len(embeddings[0]))

"""STEP 5 — Convert text into chunks"""

import faiss
import numpy as np

def build_faiss_index(embeddings):
    embeddings = np.array(embeddings).astype("float32")

    index = faiss.IndexFlatL2(embeddings.shape[1])  # L2 distance search
    index.add(embeddings)

    return index

# Build index
faiss_index = build_faiss_index(embeddings)

print("FAISS index size:", faiss_index.ntotal)

"""STEP 6 — Create FAISS Vector Store (FREE embeddings)"""

def search_faiss(query, top_k=3):
    # embed the query using the same HuggingFace model
    query_embedding = embedding_model.encode([query], convert_to_tensor=False)
    query_embedding = np.array(query_embedding).astype("float32")

    # search in FAISS
    distances, indices = faiss_index.search(query_embedding, top_k)

    # return the matching chunks
    results = [chunks[i] for i in indices[0]]
    return results

# Test search
results = search_faiss("What is the revenue of the company?")
for r in results:
    print("---- Result ----")
    print(r[:300])  # show first 300 chars

def format_context(chunks_list):
    context_text = "\n\n".join(chunks_list)
    return context_text

from langchain_google_genai import ChatGoogleGenerativeAI

# Gemini LLM
llm = ChatGoogleGenerativeAI(
    model="gemini-flash-latest",
    temperature=0.2
)

def ask_gemini(question):
    # 1. retrieve chunks
    retrieved_chunks = search_faiss(question, top_k=3)

    # 2. format them
    context = format_context(retrieved_chunks)

    # 3. build prompt for Gemini
    prompt = f"""
You are a helpful assistant. Answer the question ONLY using the below context.
If the answer is not in the context, say: 'Information not found in the PDF.'

CONTEXT:
{context}

QUESTION:
{question}

ANSWER:
"""
    # 4. call Gemini
    response = llm.invoke(prompt)
    return response